Night-Howler14/hacktoberfest22

- Library.java
I have made this file using java language .. I have made a basic code for a management of a library . I hope you will find my file helpful
> management of a library

- Library.java
Night-Howler14/hacktoberfest22#3
> management of a library""

- Bank.java
Now this is a file of java in which i made a bank management system . I added all types of authorities in it if any changes you want you can commit my changes and tell what should i add yo this file hope you like it
> Bank Management

- ques2_part1.cpp
> wertyuidsa

- animals.cpp
> QWAErtyuio

- PROJECT_1.cpp
- PROJECT_2.cpp
qwertyuioplkjhgfdsazxcvbnm123654789
> qwertyuioplkjhgfdsazxcvbnm

- Lab_7a.cpp
- Lab_7b.cpp
> qwertyuioplkjhgfdsa

- A2_q3.java
- A7_q2.c
- Java Code
- flyods_triangle.java
- q1_lab4.java
if you thing or find it helpful please merge it
> i have changed many things in the files 

- lab_5.c
> hello world

- lab_4.c
this my code hope this wil be helpful to you
> hello night howler

- A2-1.c
> this my new commit to your repository

- A3_q1.c
wertyuilmnbvcfdtyukjhvcxdfghjk
> QWERTYUIOLKJHGFSXCVBN

- A6_q3.c
rtygukhfdrtyuigyfdghjlk;jtrdserdhjlkghfdxghjkl
> fsdtuiuytdfgyuhggfdzghjkjmbhgfghjghkjl

- assig_8_2.cpp
> added nqueen problem

- merge4array.c
Kindly accept my solution.
Thank you
> Merge 4 Array

- User.java
Kindly accept my solution
Thank you
> Abstraction using Java

- mergesort4way.cpp
This is a code for 4 way merge sort
> 4 way merge sort

- bubble_sort.cpp
> Bubble sort

- dequeue_linked_list.cpp
> Dequeue Linked List

- ApplicationDemo.java
> ougougoubo

- Heap_Sort.py
A hactoberfest pull request of adding heap sort using python
> Heap_Sort using python

- assig1.cpp
- subset_sum.cpp
> noofpetrolpump

- Algorithms in Operating Systems/CPU Scheduling Algorithms/Banker's Algorithm.c
- Algorithms in Operating Systems/CPU Scheduling Algorithms/FCFS Algorithm.c
- Algorithms in Operating Systems/CPU Scheduling Algorithms/Non-Primitive Priority Scheduling Algorithm.c
- Algorithms in Operating Systems/CPU Scheduling Algorithms/SJF Algorithm.c
- Algorithms in Operating Systems/Memory Allocation Algorithms/Best Fit Algorithm.c
- Algorithms in Operating Systems/Memory Allocation Algorithms/First Fit Algorithm.c
I request you to kindly merge my PR, for adding CPU Scheduling, Memory Allocation, and Banker's Algorithm used in Operating System.
> Operating System Algorithm

- SubstringK-1DistinctElement.cpp
Code to find count of substring of length k with k-1 distinct elements using hashing
> Code to find count of substring of length k with k-1 distinct elements

- l_m_s.java
> library Management system

- combinationsum.cpp
Uploaded Combination Sum problem code
> Uploaded Combination Sum problem code

- adjmatrix.c
> qwertyrewsdfg

- circularQueue.c
> pol,mkoiuhnmnbvtyhgfcdrtyhgcfhgfghfch

- doublylinkedlist.c
> wdkjewhfofbdasijfbeiu

- dsa.c
ejfnejfnejfnefineindfiefnifnenfenfieh
> wedwdwoewoidjewoiodewddkjn
